sudo: required
language: generic

services:
    - docker

before-install:
    - docker build -t ganeshakarader/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ganeshakarader/docker-react npm run test -- --coverage
